export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST'
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'

export const CATEGORIES_VIDEOS_REQUEST = 'CATEGORIES_VIDEOS_REQUEST'
export const CATEGORIES_VIDEOS_SUCCESS = 'CATEGORIES_VIDEOS_SUCCESS'
export const CATEGORIES_VIDEOS_FAIL = 'CATEGORIES_VIDEOS_FAIL'