export const ALL_PLAYLIST_REQUEST = 'ALL_PLAYLIST_REQUEST'
export const ALL_PLAYLIST_SUCCESS = 'ALL_PLAYLIST_SUCCESS'
export const ALL_PLAYLIST_FAIL = 'ALL_PLAYLIST_FAIL'

export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS'
export const ADD_PLAYLIST_FAIL = 'ADD_PLAYLIST_FAIL'

export const ADD_VIDEO_TO_PLAYLIST_SUCCESS = 'ADD_VIDEO_TO_PLAYLIST_SUCCESS'
export const ADD_VIDEO_TO_PLAYLIST_FAIL = 'ADD_VIDEO_TO_PLAYLIST_FAIL'