export const WATCH_LATER_VIDEOS_REQUEST = 'WATCH_LATER_VIDEOS_REQUEST'
export const WATCH_LATER_VIDEOS_SUCCESS = 'WATCH_LATER_VIDEOS_SUCCESS'
export const WATCH_LATER_VIDEOS_FAIL = 'WATCH_LATER_VIDEOS_FAIL'